### PR TITLE
Setup a development mode for electron

### PR DESCRIPTION
**Pull request by erbridge**

### CODE REVIEW

**Comment by daveallenbpm** [comment]
Looks good, though windows is sad when I try to run this :(

For it to work on windows you'll need something like *SET NODE_ENV=development&& electron main.js* - the lack of a space is important otherwise it'll be included in the string. Thanks windows! I imagine unix machines wouldn't be too happy with running that command though...

It might be worth having a separate command for the windows startup, something like *start-windows* or similar. What do you think?

**Comment by erbridge** [comment]
Damned Windows... I think the best solution is actually to use something like this:

https://www.npmjs.com/package/cross-env

**Comment by daveallenbpm** [comment]
Sounds good. Love npm, there's a package for everything!

**Comment by erbridge** [comment]
`npm install` and give that a try @daveallenbpm.

**Comment by daveallenbpm** [comment]
Works for me, nice one! Good to merge

**Pull request merged**
