### PR TITLE
Add a first pass at the in level narrative

### PR DESCRIPTION
**Pull request by erbridge**
It's not pretty right now, and we're missing the girl to attach nodes to, but it works.

### CODE REVIEW

**Comment by erbridge** [comment]
The girl is now in (as a duplicate of the player sprite), the characters can move around, and I've also made it so the footsteps fade out as they get further from the camera.

**Comment by daveallenbpm** [comment]
Great work!
Love the pacing (really nicely managed with the punctuation) and nicely done with the character movements.

Happy for you to merge this in now - there are a couple of issues, mentioned below, but not game breaking, and this is a big change so probably better to get this in now and tackle them as bugs after.

As for further suggestions (listed a couple below), after this is merged we can create another issue to discuss polishing this up etc.

A couple of minor issues:
- Player animation freakout towards the end (where "No! Stop! You can't..." is on screen - related to the camera shake maybe?
- The camera pan to the first switch is interrupted and it locks back on the player before showing where the player is. 

A few ideas:
- Some kind of subtle visual indication that this is a not player controlled would be nice - something like a blur filter around the outside which fades away when the player takes control (or similar)
- Text boxes for the dialogue
- Perhaps lessen the screen shake for the antagonist's dialogue - it gets a little intense on the longer sections!
- Option to skip lines of text (one press writes rest of line, another press writes next line?)

**Comment by erbridge** [comment]
Pretty sure the camera shake is the cause of the second point. The second is because the shake overrides the tween to the first switch (which is why it sort of jumps around).

The first might be due to the movement threshold being a bit too small for the scene motion: we're using velocity rather than position to move the character, currently. It might be better to just set the character's position with a tween instead, though we'd have to work out the animation for that.

I like the blur filter idea. We could also do letterboxing which expands out at the end of the scene. Things to experiment with.

I'd like to generally touch up the screen shake to be more variable.

**Comment by mhle** [comment]
That's really cool, great work :) we should maybe show indicator to the user that cutscene is in progress, a small icon or just changing the mouse pointer to indicate control is not available.

**Comment by erbridge** [comment]
Yeah nice idea. Let's open a new issue to discuss it.

**Comment by erbridge** [comment]
See #80.

**Pull request merged**
